export const portalKeys = {
  all: ["portal"] as const,
  dashboard: () => [...portalKeys.all, "dashboard"] as const,
  setup: () => [...portalKeys.all, "setup"] as const,
  messages: () => [...portalKeys.all, "messages"] as const,
  messageThread: (id: string) => [...portalKeys.messages(), "thread", id] as const,
  meetings: () => [...portalKeys.all, "meetings"] as const,
  meeting: (id: string) => [...portalKeys.meetings(), "detail", id] as const,
  advocate: () => [...portalKeys.all, "advocate"] as const,
  sessions: () => [...portalKeys.all, "sessions"] as const,
  availability: () => [...portalKeys.all, "availability"] as const,
  documents: () => [...portalKeys.all, "documents"] as const,
  prep: () => [...portalKeys.all, "prep"] as const,
  accommodations: () => [...portalKeys.all, "accommodations"] as const,
  compensatory: () => [...portalKeys.all, "compensatory"] as const,
  journey: () => [...portalKeys.all, "journey"] as const,
  reports: () => [...portalKeys.all, "reports"] as const,
  report: (id: string) => [...portalKeys.reports(), "detail", id] as const,
};
